# Default initial positions for dual_panda's ros2_control fake system

initial_positions:
  left_panda_finger_joint1: 0.0
  left_panda_joint1: 0.0
  left_panda_joint2: -0.785
  left_panda_joint3: 0.0
  left_panda_joint4: -2.356
  left_panda_joint5: 0.0
  left_panda_joint6: 1.571
  left_panda_joint7: 0.785
  right_panda_finger_joint1: 0.0
  right_panda_joint1: 0.0
  right_panda_joint2: -0.785
  right_panda_joint3: 0.0
  right_panda_joint4: -2.356
  right_panda_joint5: 0.0
  right_panda_joint6: 1.571
  right_panda_joint7: 0.785