# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_panda_arm_controller
    - left_panda_arm_gripper_controller
    - right_panda_arm_controller
    - right_panda_arm_gripper_controller

  left_panda_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_panda_joint1
      - left_panda_joint2
      - left_panda_joint3
      - left_panda_joint4
      - left_panda_joint5
      - left_panda_joint6
      - left_panda_joint7
    action_ns: follow_joint_trajectory
    default: true
  left_panda_arm_gripper_controller:
    type: GripperCommand
    joints:
      - left_panda_finger_joint1
    action_ns: gripper_cmd
    default: true
  right_panda_arm_controller:
    type: FollowJointTrajectory
    joints:
      - right_panda_joint1
      - right_panda_joint2
      - right_panda_joint3
      - right_panda_joint4
      - right_panda_joint5
      - right_panda_joint6
      - right_panda_joint7
    action_ns: follow_joint_trajectory
    default: true
  right_panda_arm_gripper_controller:
    type: GripperCommand
    joints:
      - right_panda_finger_joint1
    action_ns: gripper_cmd
    default: true