# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_panda_arm_gripper_controller:
      type: position_controllers/GripperActionController


    right_panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_panda_arm_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_panda_arm_controller:
  ros__parameters:
    joints:
      - left_panda_joint1
      - left_panda_joint2
      - left_panda_joint3
      - left_panda_joint4
      - left_panda_joint5
      - left_panda_joint6
      - left_panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_panda_arm_gripper_controller:
  ros__parameters:
    joint: left_panda_finger_joint1
right_panda_arm_controller:
  ros__parameters:
    joints:
      - right_panda_joint1
      - right_panda_joint2
      - right_panda_joint3
      - right_panda_joint4
      - right_panda_joint5
      - right_panda_joint6
      - right_panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_panda_arm_gripper_controller:
  ros__parameters:
    joint: right_panda_finger_joint1